name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-env

      - name: Run ESLint checks
        run: npm run-script lint

      - name: Build
        run: npm run-script build

      - name: Run unit tests
        run: npm run-script test
